# Generated by Django 5.2.11 on 2026-02-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleve_nom', models.CharField(max_length=100)),
                ('eleve_postnom', models.CharField(max_length=100)),
                ('eleve_prenom', models.CharField(max_length=100)),
                ('eleve_telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('eleve_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('eleve_adresse', models.TextField(blank=True, null=True)),
                ('eleve_sexe', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=10)),
                ('eleve_date_naissance', models.DateField(blank=True, null=True)),
                ('eleve_lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anneeacademique')),
                ('classe_souhaitee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.classe')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_nom', models.CharField(max_length=100)),
                ('parent_postnom', models.CharField(max_length=100)),
                ('parent_prenom', models.CharField(max_length=100)),
                ('parent_telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_adresse', models.TextField(blank=True, null=True)),
                ('parent_sexe', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=10)),
                ('lien', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur')], max_length=30)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='admission.admissionapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('ONLINE', 'Online'), ('BUREAU', 'Bureau')], max_length=10)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.classe')),
            ],
        ),
    ]
