# Generated by Django 5.2.11 on 2026-02-24 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.eleve'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['eleve'], name='admission_i_eleve_i_bc5a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['classe'], name='admission_i_classe__c928a7_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['annee_academique'], name='admission_i_annee_a_4ca9ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('eleve', 'classe', 'annee_academique')},
        ),
    ]
