# Generated by Django 5.2.11 on 2026-02-26 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_titre_evaluation_nom_remove_cours_enseignant_and_more'),
        ('admission', '0002_initial'),
        ('users', '0003_alter_user_managers_remove_eleve_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='academics.classe'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='users.eleve'),
        ),
    ]
