# Generated by Django 5.2.11 on 2026-03-11 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_salle_sessionexamen_planificationexamen_and_more'),
        ('admission', '0003_alter_inscription_classe_alter_inscription_eleve'),
        ('core', '0001_initial'),
        ('users', '0004_alter_user_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissionguardian',
            name='parent_adresse',
            field=models.TextField(default='kolwezi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissionguardian',
            name='parent_email',
            field=models.EmailField(default='joel_email@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissionguardian',
            name='parent_telephone',
            field=models.CharField(default='0900862074', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='users.eleve'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('eleve', 'annee_academique')},
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['status'], name='admission_a_status_743f9b_idx'),
        ),
    ]
