# Generated by Django 5.2.11 on 2026-03-19 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_inscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='admissionguardian',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admissionguardian',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionguardian',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionguardian',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
