# Generated by Django 5.2.11 on 2026-03-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_eleve_created_at_eleve_updated_at_parent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(choices=[('enseignant', 'Enseignant'), ('comptable', 'Comptable'), ('agent_entretien', "Agent d'entretien"), ('secretaire', 'Secrétaire'), ('admin', 'Administrateur'), ('bibliothecaire', 'Bibliothécaire'), ('responsable_transport', 'Responsable Transport'), ('autre', 'Autre')], default='enseignant', max_length=32),
        ),
    ]
