# Generated by Django 5.2.11 on 2026-03-11 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_ecole_delete_schoolconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('type_evenement', models.CharField(choices=[('academique', 'Événement Académique'), ('sportif', 'Événement Sportif'), ('culturel', 'Événement Culturel'), ('administratif', 'Événement Administratif'), ('social', 'Événement Social'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name="Type d'événement")),
                ('date_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='planifie', max_length=20, verbose_name='Statut')),
                ('participants_attendus', models.PositiveIntegerField(default=0, verbose_name='Nombre de participants attendus')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/', verbose_name="Image de l'événement")),
                ('est_public', models.BooleanField(default=True, verbose_name='Visible publiquement')),
                ('inscription_requise', models.BooleanField(default=False, verbose_name='Inscription requise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='core.anneeacademique', verbose_name='Année académique')),
                ('organisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('nombre_accompagnants', models.PositiveIntegerField(default=0, verbose_name="Nombre d'accompagnants")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='events.event', verbose_name='Événement')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_evenements', to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Inscription à un événement',
                'verbose_name_plural': 'Inscriptions aux événements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('categorie', models.CharField(choices=[('annonce', 'Annonce'), ('succes', 'Succès'), ('info', 'Information'), ('alerte', 'Alerte'), ('nouveau', 'Nouveauté'), ('autre', 'Autre')], default='info', max_length=20, verbose_name='Catégorie')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='actualites/images/', verbose_name='Image principale')),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='actualites/fichiers/', verbose_name='Fichier joint')),
                ('est_une_alerte', models.BooleanField(default=False, verbose_name='Marquer comme alerte importante')),
                ('est_epingle', models.BooleanField(default=False, verbose_name='Épingler en haut')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Tags (séparés par des virgules)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='core.anneeacademique', verbose_name='Année académique')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-est_epingle', '-date_publication', '-created_at'],
                'indexes': [models.Index(fields=['statut'], name='events_actu_statut_b0b637_idx'), models.Index(fields=['categorie'], name='events_actu_categor_4e4a2e_idx'), models.Index(fields=['date_publication'], name='events_actu_date_pu_d1e02a_idx'), models.Index(fields=['-est_epingle', '-date_publication'], name='events_actu_est_epi_c9a259_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date_debut'], name='events_even_date_de_e71099_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type_evenement'], name='events_even_type_ev_ce95a2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['statut'], name='events_even_statut_033cef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscriptionevenement',
            unique_together={('evenement', 'participant')},
        ),
    ]
