# Generated by Django 5.2.11 on 2026-02-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HollyDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ecole', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('week_type', models.CharField(choices=[('ANGLAISE', 'Semaine anglaise (Lundi - Vendredi)'), ('NORMALE', 'Semaine normale (Lundi - Samedi)')], default='NORMALE', max_length=20)),
                ('allow_discount', models.BooleanField(default=False)),
                ('teacher_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('siblings_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('siblings_min_count', models.IntegerField(default=2)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=32, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_debut_inscriptions', models.DateField(blank=True, null=True)),
                ('date_fin_inscriptions', models.DateField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['actif'], name='core_anneea_actif_62075b_idx'), models.Index(fields=['date_debut', 'date_fin'], name='core_anneea_date_de_66e5b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=50)),
                ('trimestre', models.CharField(choices=[('trimestre_1', '1er Trimestre'), ('trimestre_2', '2e Trimestre'), ('trimestre_3', '3e Trimestre')], default='trimestre_1', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='core.anneeacademique')),
            ],
            options={
                'indexes': [models.Index(fields=['annee_academique'], name='core_period_annee_a_36d06c_idx'), models.Index(fields=['date_debut', 'date_fin'], name='core_period_date_de_478dae_idx'), models.Index(fields=['actif'], name='core_period_actif_6e4c8d_idx')],
                'unique_together': {('nom', 'annee_academique')},
            },
        ),
    ]
