# Generated by Django 5.2.11 on 2026-03-11 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_salle_sessionexamen_planificationexamen_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="Username sauvegardé (au cas où l'utilisateur est supprimé)", max_length=150)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('failed_login', 'Connexion Échouée'), ('permission_denied', 'Permission Refusée'), ('other', 'Autre')], db_index=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, help_text="Représentation textuelle de l'objet", max_length=500)),
                ('model_name', models.CharField(blank=True, db_index=True, help_text='Nom du modèle (ex: User, Classe, Note)', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description de l'action")),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Détails des changements (ancien/nouveau)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent du navigateur')),
                ('request_path', models.CharField(blank=True, help_text='Chemin de la requête HTTP', max_length=500)),
                ('request_method', models.CharField(blank=True, help_text='Méthode HTTP (GET, POST, PUT, DELETE)', max_length=10)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failure', 'Échec'), ('error', 'Erreur')], db_index=True, default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur si échec")),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text="Utilisateur ayant effectué l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'Audit",
                'verbose_name_plural': "Logs d'Audit",
                'db_table': 'common_auditlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='common_audi_user_id_740557_idx'), models.Index(fields=['action', 'timestamp'], name='common_audi_action_6014bc_idx'), models.Index(fields=['model_name', 'timestamp'], name='common_audi_model_n_72aaa5_idx'), models.Index(fields=['status'], name='common_audi_status_df7d05_idx'), models.Index(fields=['timestamp'], name='common_audi_timesta_4ebe40_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_document', models.CharField(choices=[('bulletin', 'Bulletin'), ('facture', 'Facture'), ('recu', 'Reçu'), ('certificat', 'Certificat'), ('rapport', 'Rapport'), ('photo', 'Photo'), ('autre', 'Autre')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('file_path', models.CharField(help_text='Chemin du fichier dans le stockage (S3/MinIO)', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Taille du fichier en octets')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, help_text="Date d'expiration du document", null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Document archivé')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Accessible publiquement')),
                ('checksum', models.CharField(blank=True, help_text='Checksum MD5/SHA256 du fichier', max_length=64)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'common_document',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['type_document'], name='common_docu_type_do_9dba85_idx'), models.Index(fields=['uploaded_by'], name='common_docu_uploade_f7992f_idx'), models.Index(fields=['uploaded_at'], name='common_docu_uploade_957ec8_idx'), models.Index(fields=['is_archived'], name='common_docu_is_arch_0d9e3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReglePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('moyenne_minimale', models.DecimalField(decimal_places=2, help_text='Moyenne minimale requise pour la promotion', max_digits=5)),
                ('taux_presence_minimal', models.DecimalField(decimal_places=2, default=75, help_text='Taux de présence minimal en pourcentage', max_digits=5)),
                ('est_active', models.BooleanField(default=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_promotion', to='core.anneeacademique')),
                ('classe_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_promotion_destination', to='academics.classe')),
                ('classe_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_promotion_origine', to='academics.classe')),
            ],
            options={
                'verbose_name': 'Règle de Promotion',
                'verbose_name_plural': 'Règles de Promotion',
                'db_table': 'core_reglepromotion',
                'indexes': [models.Index(fields=['classe_origine'], name='core_reglep_classe__e46b3a_idx'), models.Index(fields=['annee_academique'], name='core_reglep_annee_a_6df5ed_idx'), models.Index(fields=['est_active'], name='core_reglep_est_act_8fbfc2_idx')],
                'unique_together': {('classe_origine', 'annee_academique')},
            },
        ),
    ]
