# Generated by Django 5.2.11 on 2026-03-11 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_document_reglepromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('site_web', models.URLField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('devise', models.CharField(blank=True, help_text="Slogan de l'école", max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('week_type', models.CharField(choices=[('ANGLAISE', 'Semaine anglaise (Lundi - Vendredi)'), ('NORMALE', 'Semaine normale (Lundi - Samedi)')], default='NORMALE', max_length=20)),
                ('allow_discount', models.BooleanField(default=False)),
                ('teacher_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('siblings_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('siblings_min_count', models.IntegerField(default=2)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'db_table': 'core_ecole',
            },
        ),
        migrations.DeleteModel(
            name='SchoolConfiguration',
        ),
        migrations.AlterModelOptions(
            name='anneeacademique',
            options={'verbose_name': 'Année Académique', 'verbose_name_plural': 'Années Académiques'},
        ),
        migrations.AlterModelOptions(
            name='hollydays',
            options={'verbose_name': 'Jour Férié', 'verbose_name_plural': 'Jours Fériés'},
        ),
        migrations.AlterModelOptions(
            name='periode',
            options={'verbose_name': 'Période', 'verbose_name_plural': 'Périodes'},
        ),
        migrations.AddField(
            model_name='reglepromotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reglepromotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='anneeacademique',
            table='core_anneeacademique',
        ),
        migrations.AlterModelTable(
            name='hollydays',
            table='core_hollydays',
        ),
        migrations.AlterModelTable(
            name='periode',
            table='core_periode',
        ),
    ]
