# Generated by Django 5.2.11 on 2026-03-12 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ecole_delete_schoolconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeacademique',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anneeacademique',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='periode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
