# Generated by Django 5.2.11 on 2026-03-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_anneeacademique_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='duree_heure_etude',
            field=models.PositiveIntegerField(default=50, help_text="Durée d'une heure d'étude en minutes (ex: 50)"),
        ),
        migrations.AddField(
            model_name='ecole',
            name='duree_recreation',
            field=models.PositiveIntegerField(default=30, help_text='Durée de la récréation en minutes (ex: 30)'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='heure_debut_cours',
            field=models.TimeField(default='07:30', help_text="Heure de début de la 1ère heure d'étude (ex: 07:30)"),
        ),
        migrations.AddField(
            model_name='ecole',
            name='heure_recreation_apres',
            field=models.PositiveIntegerField(default=3, help_text="La récréation vient après quelle heure d'étude (ex: 3 = après la 3e heure)"),
        ),
    ]
