# Generated by Django 5.2.11 on 2026-03-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schedule_timing_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='taux_heure_supplementaire_defaut',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Montant fixé payé par heure supplémentaire (en devise locale). Utilisé comme valeur par défaut lors de la création d'un nouveau contrat.", max_digits=12),
        ),
        migrations.AddField(
            model_name='ecole',
            name='taux_retenue_absence_defaut',
            field=models.DecimalField(decimal_places=2, default=100, help_text="Taux de retenue (%) apppliqué par jour d'absence non justifié. 100 = 1 journée complète. Utilisé comme valeur par défaut lors de la création d'un nouveau contrat.", max_digits=5),
        ),
    ]
