# Generated by Django 5.2.11 on 2026-03-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_rh_taux_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='biblio_jours_avant_penalite',
            field=models.PositiveIntegerField(default=0, help_text="Nombre de jours de tolérance après la date limite avant d'appliquer la pénalité (0 = immédiat)"),
        ),
        migrations.AddField(
            model_name='ecole',
            name='biblio_montant_penalite',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la pénalité', max_digits=12),
        ),
        migrations.AddField(
            model_name='ecole',
            name='biblio_type_penalite',
            field=models.CharField(choices=[('FIXE', 'Montant Fixe'), ('PAR_JOUR', 'Taux par jour de retard')], default='FIXE', max_length=20),
        ),
    ]
