# Generated by Django 5.2.11 on 2026-02-24 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compteeleve',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='users.eleve'),
        ),
        migrations.AddField(
            model_name='detteeleve',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.eleve'),
        ),
        migrations.AddField(
            model_name='facture',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.eleve'),
        ),
        migrations.AddField(
            model_name='frais',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anneeacademique'),
        ),
        migrations.AddField(
            model_name='frais',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.classe'),
        ),
        migrations.AddField(
            model_name='detteeleve',
            name='frais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.frais'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.eleve'),
        ),
        migrations.AddField(
            model_name='facture',
            name='paiement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='finance.paiement'),
        ),
        migrations.AddField(
            model_name='paiementallocation',
            name='dette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.detteeleve'),
        ),
        migrations.AddField(
            model_name='paiementallocation',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.paiement'),
        ),
        migrations.AlterUniqueTogether(
            name='compteeleve',
            unique_together={('eleve', 'annee_academique')},
        ),
        migrations.AlterUniqueTogether(
            name='frais',
            unique_together={('nom', 'classe', 'annee_academique')},
        ),
        migrations.AddIndex(
            model_name='detteeleve',
            index=models.Index(fields=['eleve', 'statut'], name='finance_det_eleve_i_ebda7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detteeleve',
            unique_together={('eleve', 'frais')},
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['eleve', 'statut'], name='finance_pai_eleve_i_cbdf67_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['created_at'], name='finance_pai_created_5531b9_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementallocation',
            index=models.Index(fields=['paiement'], name='finance_pai_paiemen_3838ae_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementallocation',
            index=models.Index(fields=['dette'], name='finance_pai_dette_i_5744f8_idx'),
        ),
    ]
