# Generated by Django 5.2.11 on 2026-03-17 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schedule_timing_volume'),
        ('finance', '0002_initial'),
        ('users', '0005_eleve_created_at_eleve_updated_at_parent_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('mois', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annee', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Banque'), ('MOBILE', 'Mobile Money')], max_length=10)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirme'), ('CANCELLED', 'Annule')], default='PENDING', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.anneeacademique')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_salary_payments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_salary_payments', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_salaire', to='users.personnel')),
            ],
            options={
                'indexes': [models.Index(fields=['personnel', 'statut'], name='finance_pai_personn_5726e9_idx'), models.Index(fields=['annee', 'mois'], name='finance_pai_annee_fa7224_idx'), models.Index(fields=['created_at'], name='finance_pai_created_361903_idx')],
            },
        ),
    ]
