# Generated by Django 5.2.11 on 2026-03-18 10:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_paiementsalaire'),
        ('users', '0005_eleve_created_at_eleve_updated_at_parent_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('STAGE', 'Stage'), ('INTERIM', 'Intérim'), ('AUTRE', 'Autre')], default='CDI', max_length=20)),
                ('poste', models.CharField(help_text='Intitulé du poste occupé (ex: Enseignant de Mathématiques)', max_length=150)),
                ('date_debut', models.DateField(help_text='Date de début du contrat')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin (laisser vide pour un CDI)', null=True)),
                ('salaire_base', models.DecimalField(decimal_places=2, help_text='Salaire de base mensuel brut', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('nb_jours_ouvrable', models.PositiveSmallIntegerField(default=26, help_text='Nombre de jours ouvrables par mois (défaut: 26)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('taux_retenue_absence', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text="% du salaire journalier à retrancher par jour d'absence (100% = 1 journée complète)", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('taux_heure_supplementaire', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant fixe payé par heure supplémentaire', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('prime_motivation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Prime de motivation mensuelle fixe incluse dans le contrat', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('observations', models.TextField(blank=True, help_text='Observations ou conditions particulières du contrat', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_crees', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='users.personnel')),
            ],
            options={
                'verbose_name': 'Contrat Employé',
                'verbose_name_plural': 'Contrats Employés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulletinSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annee', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('salaire_base', models.DecimalField(decimal_places=2, help_text='Salaire de base (copié depuis le contrat)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('nb_jours_absence', models.PositiveSmallIntegerField(default=0, help_text="Nombre de jours d'absence non justifiés")),
                ('retenue_absence', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant retranché au titre des absences (calculé automatiquement)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('nb_heures_supplementaires', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Nombre d'heures supplémentaires effectuées", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('montant_heures_sup', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant ajouté pour les heures supplémentaires (calculé automatiquement)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('prime_motivation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Prime de motivation ce mois-ci (peut différer du contrat)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('autres_primes', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Autres primes exceptionnelles (bonus, ancienneté, etc.)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note_primes', models.TextField(blank=True, help_text='Description des primes supplémentaires', null=True)),
                ('autres_retenues', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Autres retenues (avances, pénalités, etc.)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note_retenues', models.TextField(blank=True, help_text='Description des retenues supplémentaires', null=True)),
                ('salaire_net', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Salaire net à payer (calculé automatiquement)', max_digits=12)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('PAYE', 'Payé')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins_crees', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.OneToOneField(blank=True, help_text='Paiement associé lorsque le bulletin est payé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletin', to='finance.paiementsalaire')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins_salaire', to='users.personnel')),
                ('contrat', models.ForeignKey(help_text='Contrat en vigueur au moment de la génération du bulletin', on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='finance.contratemploye')),
            ],
            options={
                'verbose_name': 'Bulletin de Salaire',
                'verbose_name_plural': 'Bulletins de Salaire',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.AddIndex(
            model_name='contratemploye',
            index=models.Index(fields=['personnel', 'statut'], name='finance_con_personn_8b9839_idx'),
        ),
        migrations.AddIndex(
            model_name='contratemploye',
            index=models.Index(fields=['date_debut', 'date_fin'], name='finance_con_date_de_52991a_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletinsalaire',
            index=models.Index(fields=['personnel', 'statut'], name='finance_bul_personn_0c170f_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletinsalaire',
            index=models.Index(fields=['annee', 'mois'], name='finance_bul_annee_119169_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletinsalaire',
            index=models.Index(fields=['created_at'], name='finance_bul_created_cfc266_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bulletinsalaire',
            unique_together={('personnel', 'mois', 'annee')},
        ),
    ]
