# Generated by Django 5.2.11 on 2026-03-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_contrat_employe_bulletin_salaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratemploye',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contratemploye',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='paiementsalaire',
            name='annee_academique',
        ),
        migrations.RemoveField(
            model_name='paiementsalaire',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='paiementsalaire',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paiementsalaire',
            name='personnel',
        ),
        migrations.DeleteModel(
            name='BulletinSalaire',
        ),
        migrations.DeleteModel(
            name='ContratEmploye',
        ),
        migrations.DeleteModel(
            name='PaiementSalaire',
        ),
    ]
