# Generated by Django 5.2.11 on 2026-03-19 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code_barre', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USE', 'Usé'), ('ABIME', 'Abîmé'), ('PERDU', 'Perdu')], default='NEUF', max_length=20)),
                ('est_disponible', models.BooleanField(default=True)),
                ('date_acquisition', models.DateField(auto_now_add=True)),
                ('prix_acquisition', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarque', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_RETARD', 'En retard'), ('RETOURNE', 'Retourné'), ('PERDU', 'Déclaré perdu')], default='EN_COURS', max_length=20)),
                ('remarque_emprunt', models.TextField(blank=True)),
                ('remarque_retour', models.TextField(blank=True)),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts_bibliotheque', to=settings.AUTH_USER_MODEL)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprunts_enregistres', to=settings.AUTH_USER_MODEL)),
                ('retour_enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retours_enregistres', to=settings.AUTH_USER_MODEL)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historique_emprunts', to='bibliotheque.exemplaire')),
            ],
            options={
                'ordering': ['-date_emprunt'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('nom', models.CharField(help_text='Ex: Inventaire Annuel 2026', max_length=255)),
                ('en_cours', models.BooleanField(default=True)),
                ('observations', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_constate', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USE', 'Usé'), ('ABIME', 'Abîmé'), ('PERDU', 'Perdu')], max_length=20)),
                ('est_present', models.BooleanField(default=True)),
                ('remarque', models.TextField(blank=True)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.exemplaire')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bibliotheque.inventaire')),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('langue', models.CharField(default='Français', max_length=50)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bibliotheque/livres/')),
            ],
            options={
                'ordering': ['titre'],
                'indexes': [models.Index(fields=['titre'], name='bibliothequ_titre_4302b6_idx'), models.Index(fields=['auteur'], name='bibliothequ_auteur_e77807_idx'), models.Index(fields=['isbn'], name='bibliothequ_isbn_44aa55_idx')],
            },
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='bibliotheque.livre'),
        ),
        migrations.CreateModel(
            name='PaiementAmende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE', 'Mobile Money'), ('BANK', 'Virement Bancaire')], default='CASH', max_length=20)),
                ('motif', models.CharField(default='Retard de retour', max_length=255)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('emprunt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendes', to='bibliotheque.emprunt')),
                ('percu_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['statut'], name='bibliothequ_statut_e60ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['date_emprunt'], name='bibliothequ_date_em_0ea392_idx'),
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['date_retour_prevue'], name='bibliothequ_date_re_4bfa01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ligneinventaire',
            unique_together={('inventaire', 'exemplaire')},
        ),
        migrations.AddIndex(
            model_name='exemplaire',
            index=models.Index(fields=['code_barre'], name='bibliothequ_code_ba_4396c3_idx'),
        ),
        migrations.AddIndex(
            model_name='exemplaire',
            index=models.Index(fields=['est_disponible'], name='bibliothequ_est_dis_061ed2_idx'),
        ),
    ]
