# Generated by Django 5.2.11 on 2026-03-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='montant_penalite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='penalite_payee',
            field=models.BooleanField(default=False),
        ),
    ]
