# Generated by Django 5.2.11 on 2026-02-24 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='notification_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.notificationuser'),
        ),
        migrations.AddIndex(
            model_name='notificationuser',
            index=models.Index(fields=['user', 'is_read'], name='communicati_user_id_eaead0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationuser',
            unique_together={('notification', 'user')},
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['canal', 'status'], name='communicati_canal_5e0d61_idx'),
        ),
    ]
