# Generated by Django 5.2.11 on 2026-03-11 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_salle_sessionexamen_planificationexamen_and_more'),
        ('communication', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_room', models.CharField(choices=[('classe', 'Chat de Classe'), ('groupe', 'Groupe Privé'), ('general', 'Général')], default='classe', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_modere', models.BooleanField(default=True, help_text='Les messages nécessitent une modération')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(blank=True, help_text='Classe associée (pour type=classe)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='academics.classe')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salle de Chat',
                'verbose_name_plural': 'Salles de Chat',
                'db_table': 'communication_chatroom',
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('membre', 'Membre'), ('moderateur', 'Modérateur'), ('admin', 'Administrateur')], default='membre', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, help_text='Dernière lecture des messages', null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communication.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre de Chat',
                'verbose_name_plural': 'Membres de Chat',
                'db_table': 'communication_chatroommember',
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='membres',
            field=models.ManyToManyField(related_name='chat_rooms', through='communication.ChatRoomMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('notes_published', models.BooleanField(default=True, help_text='Notifications pour publication de notes')),
                ('absences', models.BooleanField(default=True, help_text='Notifications pour absences')),
                ('paiements', models.BooleanField(default=True, help_text='Notifications pour paiements')),
                ('annonces', models.BooleanField(default=True, help_text='Notifications pour annonces générales')),
                ('chat_messages', models.BooleanField(default=True, help_text='Notifications pour messages de chat')),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immédiat'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('disabled', 'Désactivé')], default='immediate', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Début des heures silencieuses', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Fin des heures silencieuses', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de Notification',
                'verbose_name_plural': 'Préférences de Notifications',
                'db_table': 'communication_notificationpreference',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type_message', models.CharField(choices=[('text', 'Texte'), ('file', 'Fichier'), ('image', 'Image'), ('system', 'Message Système')], default='text', max_length=20)),
                ('file_url', models.CharField(blank=True, help_text='URL du fichier attaché', max_length=500, null=True)),
                ('is_moderated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.chatroom')),
            ],
            options={
                'verbose_name': 'Message de Chat',
                'verbose_name_plural': 'Messages de Chat',
                'db_table': 'communication_chatmessage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room'], name='communicati_room_id_ec89e1_idx'), models.Index(fields=['sender'], name='communicati_sender__ae256d_idx'), models.Index(fields=['created_at'], name='communicati_created_fb6ccb_idx'), models.Index(fields=['is_deleted'], name='communicati_is_dele_e95520_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatroommember',
            index=models.Index(fields=['room'], name='communicati_room_id_511c64_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroommember',
            index=models.Index(fields=['user'], name='communicati_user_id_feee03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroommember',
            unique_together={('room', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['type_room'], name='communicati_type_ro_a7af72_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['classe'], name='communicati_classe__68689b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['actif'], name='communicati_actif_f6ab7c_idx'),
        ),
    ]
