# Generated by Django 5.2.11 on 2026-03-19 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_chatroom_chatroommember_chatroom_membres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(blank=True, help_text='Clé secrète (optionnelle)', max_length=128, null=True)),
                ('events', models.JSONField(default=list, help_text="Liste des événements (ex: ['paiement.created', 'eleve.created'])")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Endpoint Webhook',
                'verbose_name_plural': 'Endpoints Webhooks',
                'db_table': 'communication_webhookendpoint',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='communication.webhookendpoint')),
            ],
            options={
                'db_table': 'communication_webhookdelivery',
                'ordering': ['-created_at'],
            },
        ),
    ]
