# Generated by Django 5.2.11 on 2026-02-24 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='comptabilit_date_7bd094_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='comptabilit_referen_d31a0e_idx'),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.account'),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='comptabilite.transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('year', 'month')},
        ),
        migrations.AddIndex(
            model_name='transactionline',
            index=models.Index(fields=['account'], name='comptabilit_account_6f4a71_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionline',
            index=models.Index(fields=['transaction'], name='comptabilit_transac_d754c6_idx'),
        ),
    ]
