# Generated by Django 5.2.11 on 2026-02-24 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('titulaire', 'Titulaire'), ('remplacant', 'Remplaçant')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('mention', models.CharField(blank=True, max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(choices=[('creche', 'Crèche'), ('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('humanite', 'Humanité')], default='primaire', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type_evaluation', models.CharField(choices=[('interro', 'Interrogation'), ('devoir', 'Devoir'), ('examen', 'Examen'), ('autre', 'Autre')], default='autre', max_length=32)),
                ('titre', models.CharField(max_length=100)),
                ('bareme', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('valeur', models.FloatField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
