# Generated by Django 5.2.11 on 2026-02-24 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationenseignant',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personnel'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneeacademique'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='users.eleve'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periode'),
        ),
        migrations.AddField(
            model_name='classe',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='core.anneeacademique'),
        ),
        migrations.AddField(
            model_name='classe',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_dirigees', to='users.personnel'),
        ),
        migrations.AddField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academics.classe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='users.personnel'),
        ),
        migrations.AddField(
            model_name='affectationenseignant',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.cours'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anneeacademique'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.cours'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.periode'),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.eleve'),
        ),
        migrations.AddField(
            model_name='note',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.evaluation'),
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['eleve', 'annee_academique'], name='academics_b_eleve_i_1ef5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['periode'], name='academics_b_periode_ff7d52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bulletin',
            unique_together={('eleve', 'periode', 'annee_academique')},
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['annee_academique'], name='academics_c_annee_a_57e711_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['niveau'], name='academics_c_niveau_9dc0af_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['actif'], name='academics_c_actif_396e0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'annee_academique')},
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['code'], name='academics_c_code_d43109_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['classe'], name='academics_c_classe__20fed3_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['actif'], name='academics_c_actif_d98f61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together={('code', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='affectationenseignant',
            unique_together={('teacher', 'cours', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['cours'], name='academics_e_cours_i_427786_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['periode'], name='academics_e_periode_da0a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['eleve'], name='academics_n_eleve_i_d94448_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['evaluation'], name='academics_n_evaluat_144637_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('eleve', 'evaluation')},
        ),
    ]
