# Generated by Django 5.2.11 on 2026-03-11 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_titre_evaluation_nom_remove_cours_enseignant_and_more'),
        ('core', '0001_initial'),
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Code unique de la salle (ex: A101, B205)', max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('batiment', models.CharField(blank=True, help_text='Nom du bâtiment', max_length=100, null=True)),
                ('capacite', models.IntegerField(help_text='Capacité maximale en nombre de places')),
                ('type_salle', models.CharField(choices=[('classe', 'Classe'), ('examen', "Salle d'examen"), ('labo', 'Laboratoire'), ('amphi', 'Amphithéâtre')], default='classe', max_length=50)),
                ('equipements', models.TextField(blank=True, help_text='Liste des équipements disponibles', null=True)),
                ('est_disponible', models.BooleanField(default=True, help_text='Salle disponible pour utilisation')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'db_table': 'academics_salle',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='academics_s_code_a96724_idx'), models.Index(fields=['type_salle'], name='academics_s_type_sa_41f377_idx'), models.Index(fields=['est_disponible'], name='academics_s_est_dis_a169c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(help_text='Nom de la session (ex: Examens 1er Trimestre 2026)', max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_session', models.CharField(choices=[('interrogation', 'Interrogations'), ('examen_partiel', 'Examen Partiel'), ('examen_final', 'Examen Final')], default='examen_final', max_length=50)),
                ('instructions', models.TextField(blank=True, help_text='Instructions générales pour cette session', null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé')], db_index=True, default='planifie', max_length=20)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_examen', to='core.periode')),
            ],
            options={
                'verbose_name': "Session d'Examen",
                'verbose_name_plural': "Sessions d'Examens",
                'db_table': 'academics_sessionexamen',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PlanificationExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_examen', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_minutes', models.IntegerField(help_text="Durée de l'examen en minutes")),
                ('instructions_surveillants', models.TextField(blank=True, help_text='Instructions pour les surveillants', null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to='academics.evaluation')),
                ('surveillants', models.ManyToManyField(blank=True, limit_choices_to={'fonction': 'enseignant'}, related_name='surveillances', to='users.personnel')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications_examen', to='academics.salle')),
                ('session_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to='academics.sessionexamen')),
            ],
            options={
                'verbose_name': "Planification d'Examen",
                'verbose_name_plural': "Planifications d'Examens",
                'db_table': 'academics_planificationexamen',
                'ordering': ['date_examen', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='RepartitionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_place', models.IntegerField(help_text='Numéro de place assigné dans la salle')),
                ('zone', models.CharField(blank=True, help_text='Zone dans la salle (ex: A, B, C)', max_length=50, null=True)),
                ('rangee', models.IntegerField(blank=True, help_text='Numéro de rangée', null=True)),
                ('colonne', models.IntegerField(blank=True, help_text='Numéro de colonne', null=True)),
                ('instructions_speciales', models.TextField(blank=True, help_text='Instructions spéciales pour cet élève (ex: besoin particulier)', null=True)),
                ('est_present', models.BooleanField(default=False, help_text="L'élève s'est présenté à l'examen")),
                ('heure_arrivee', models.DateTimeField(blank=True, help_text="Heure d'arrivée de l'élève", null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartitions_examen', to='users.eleve')),
                ('planification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartitions', to='academics.planificationexamen')),
            ],
            options={
                'verbose_name': "Répartition d'Examen",
                'verbose_name_plural': "Répartitions d'Examens",
                'db_table': 'academics_repartitionexamen',
                'ordering': ['planification', 'numero_place'],
                'indexes': [models.Index(fields=['planification'], name='academics_r_planifi_8a573b_idx'), models.Index(fields=['eleve'], name='academics_r_eleve_i_ebc77f_idx'), models.Index(fields=['numero_place'], name='academics_r_numero__58ecd5_idx')],
                'unique_together': {('planification', 'eleve'), ('planification', 'numero_place')},
            },
        ),
        migrations.AddIndex(
            model_name='sessionexamen',
            index=models.Index(fields=['periode'], name='academics_s_periode_a17962_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionexamen',
            index=models.Index(fields=['date_debut', 'date_fin'], name='academics_s_date_de_862e42_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionexamen',
            index=models.Index(fields=['statut'], name='academics_s_statut_d5853e_idx'),
        ),
        migrations.AddIndex(
            model_name='planificationexamen',
            index=models.Index(fields=['evaluation'], name='academics_p_evaluat_226f67_idx'),
        ),
        migrations.AddIndex(
            model_name='planificationexamen',
            index=models.Index(fields=['salle'], name='academics_p_salle_i_49eded_idx'),
        ),
        migrations.AddIndex(
            model_name='planificationexamen',
            index=models.Index(fields=['date_examen'], name='academics_p_date_ex_840afe_idx'),
        ),
        migrations.AddIndex(
            model_name='planificationexamen',
            index=models.Index(fields=['session_examen'], name='academics_p_session_803d28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planificationexamen',
            unique_together={('salle', 'date_examen', 'heure_debut')},
        ),
    ]
