# Generated by Django 5.2.11 on 2026-03-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_affectationenseignant_created_at_and_more'),
        ('core', '0005_schedule_timing_volume'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together={('code', 'classe')},
        ),
        migrations.AddField(
            model_name='cours',
            name='volume_horaire',
            field=models.PositiveIntegerField(default=1, help_text="Volume horaire hebdomadaire (poids relatif pour la génération d'horaire). Ex: 4 = 4h/semaine"),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['annee_academique'], name='academics_c_annee_a_46078c_idx'),
        ),
    ]
