# Generated by Django 5.2.11 on 2026-03-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_add_rh_taux_ecole'),
        ('users', '0005_eleve_created_at_eleve_updated_at_parent_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArretBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(help_text='Ex: Rond-point Ngaba', max_length=100, unique=True)),
                ('adresse', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(help_text='Numéro du bus (ex: Bus 01)', max_length=20, unique=True)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('capacite', models.PositiveIntegerField(help_text='Nombre total de places assises')),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('chauffeur', models.CharField(blank=True, help_text='Nom du chauffeur principal', max_length=150)),
                ('contact_chauffeur', models.CharField(blank=True, max_length=20)),
                ('est_operationnel', models.BooleanField(default=True)),
                ('remarques', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(help_text='Ex: Ligne Rouge (Centre-ville)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneeacademique')),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraires', to='transport.bus')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('nom', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='ArretItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(help_text='Position dans le parcours (1, 2, 3...)')),
                ('heure_passage_matin', models.TimeField(blank=True, help_text='Heure de ramassage', null=True)),
                ('heure_passage_soir', models.TimeField(blank=True, help_text='Heure de dépose', null=True)),
                ('arret', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.arretbus')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='transport.itineraire')),
            ],
            options={
                'ordering': ['itineraire', 'ordre'],
                'unique_together': {('itineraire', 'arret')},
            },
        ),
        migrations.CreateModel(
            name='AffectationEleveTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneeacademique')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='users.eleve')),
                ('arret_descente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descentes', to='transport.arretitineraire')),
                ('arret_montee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='montees', to='transport.arretitineraire')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves_affectes', to='transport.itineraire')),
            ],
            options={
                'unique_together': {('eleve', 'annee_academique')},
            },
        ),
    ]
