# Generated by Django 5.2.11 on 2026-03-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        ('users', '0006_alter_personnel_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='chauffeur',
            field=models.ForeignKey(blank=True, help_text='Chauffeur principal du bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_conduits', to='users.personnel'),
        ),
    ]
