# Generated by Django 5.2.11 on 2026-03-19 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_rh_taux_ecole'),
        ('transport', '0002_alter_bus_chauffeur'),
        ('users', '0006_alter_personnel_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='chauffeur',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='contact_chauffeur',
        ),
        migrations.CreateModel(
            name='AffectationChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True, help_text='Indique si le chauffeur assure actuellement ce trajet')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneeacademique')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_transport', to='users.personnel')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeurs_affectes', to='transport.itineraire')),
            ],
            options={
                'unique_together': {('chauffeur', 'itineraire', 'annee_academique')},
            },
        ),
    ]
