# Generated by Django 5.2.11 on 2026-03-19 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_remove_bus_chauffeur_remove_bus_contact_chauffeur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraire',
            name='bus',
        ),
        migrations.AddField(
            model_name='affectationchauffeur',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations_chauffeur', to='transport.bus'),
        ),
    ]
