# Generated by Django 5.2.11 on 2026-02-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.eleve'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periode'),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.eleve'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.anneeacademique'),
        ),
        migrations.AddField(
            model_name='horairecours',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anneeacademique'),
        ),
        migrations.AddField(
            model_name='horairecours',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classe'),
        ),
        migrations.AddField(
            model_name='horairecours',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.cours'),
        ),
        migrations.AddField(
            model_name='presence',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='users.eleve'),
        ),
        migrations.AddField(
            model_name='justificationabsence',
            name='presence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.presence'),
        ),
        migrations.AddField(
            model_name='seancecours',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anneeacademique'),
        ),
        migrations.AddField(
            model_name='seancecours',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.classe'),
        ),
        migrations.AddField(
            model_name='seancecours',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.cours'),
        ),
        migrations.AddField(
            model_name='seancecours',
            name='horaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.horairecours'),
        ),
        migrations.AddField(
            model_name='presence',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='attendance.seancecours'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('eleve', 'periode')},
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['eleve'], name='attendance__eleve_i_645df1_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['seance'], name='attendance__seance__de1de7_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['statut'], name='attendance__statut_fbb32a_idx'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('eleve', 'seance'), name='eleve_seance_unique_presence'),
        ),
    ]
