# Generated by Django 5.2.11 on 2026-03-17 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_schedule_timing_volume'),
        ('attendance', '0003_disciplinerecord_created_at_and_more'),
        ('core', '0005_schedule_timing_volume'),
        ('users', '0005_eleve_created_at_eleve_updated_at_parent_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseHoraireConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_max_par_jour', models.PositiveIntegerField(default=6, help_text="Nombre maximum d'heures d'étude par jour pour cette classe (ex: 6 ou 8)")),
                ('jours_prolonges', models.JSONField(blank=True, default=list, help_text='Jours avec des heures supplémentaires (au-delà de 6), ex: ["LUNDI","MERCREDI"]. Ignorer si heures_max_par_jour <= 6.')),
            ],
            options={
                'verbose_name': 'Config Horaire Classe',
                'verbose_name_plural': 'Configs Horaire Classes',
                'db_table': 'attendance_classehoraireconfig',
            },
        ),
        migrations.CreateModel(
            name='HoraireEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horaire Enseignant',
                'verbose_name_plural': 'Horaires Enseignants',
                'db_table': 'attendance_horaireenseignant',
                'ordering': ['horaire_cours__jour', 'horaire_cours__numero_heure'],
            },
        ),
        migrations.AlterModelOptions(
            name='horairecours',
            options={'ordering': ['jour', 'numero_heure', 'heure_debut']},
        ),
        migrations.AddField(
            model_name='horairecours',
            name='numero_heure',
            field=models.PositiveIntegerField(blank=True, help_text="Numéro de l'heure dans la journée (1=1ère heure, 2=2e heure, ...)", null=True),
        ),
        migrations.AlterField(
            model_name='horairecours',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='academics.classe'),
        ),
        migrations.AlterField(
            model_name='horairecours',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='academics.cours'),
        ),
        migrations.AddIndex(
            model_name='horairecours',
            index=models.Index(fields=['classe', 'jour'], name='attendance__classe__80b601_idx'),
        ),
        migrations.AddIndex(
            model_name='horairecours',
            index=models.Index(fields=['cours'], name='attendance__cours_i_ce9e21_idx'),
        ),
        migrations.AddIndex(
            model_name='horairecours',
            index=models.Index(fields=['annee_academique'], name='attendance__annee_a_9ed076_idx'),
        ),
        migrations.AddField(
            model_name='classehoraireconfig',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horaire_configs', to='core.anneeacademique'),
        ),
        migrations.AddField(
            model_name='classehoraireconfig',
            name='classe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horaire_config', to='academics.classe'),
        ),
        migrations.AddField(
            model_name='horaireenseignant',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horaires_enseignants', to='core.anneeacademique'),
        ),
        migrations.AddField(
            model_name='horaireenseignant',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_enseignant', to='users.personnel'),
        ),
        migrations.AddField(
            model_name='horaireenseignant',
            name='horaire_cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_enseignants', to='attendance.horairecours'),
        ),
        migrations.AddIndex(
            model_name='horaireenseignant',
            index=models.Index(fields=['enseignant', 'annee_academique'], name='attendance__enseign_92c7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='horaireenseignant',
            index=models.Index(fields=['horaire_cours'], name='attendance__horaire_6505c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='horaireenseignant',
            unique_together={('enseignant', 'horaire_cours')},
        ),
    ]
