# Generated by Django 5.2.11 on 2026-03-19 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_schedule_timing_volume'),
        ('users', '0005_eleve_created_at_eleve_updated_at_parent_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(help_text='Journée concernée')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('remplace', 'Remplacé'), ('conge', 'Congé')], default='present', max_length=16)),
                ('conge_justifie', models.BooleanField(default=False, help_text='Absence justifiée (congé maladie, congé payé, etc.) — non déduit de la paie')),
                ('remarque', models.TextField(blank=True, null=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_personnel_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_travail', to='users.personnel')),
                ('remplacant', models.ForeignKey(blank=True, help_text='Personnel remplaçant (si statut=remplace)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacements', to='users.personnel')),
            ],
            options={
                'verbose_name': 'Présence Personnel',
                'verbose_name_plural': 'Présences Personnel',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['personnel', 'date'], name='attendance__personn_4a0c33_idx'), models.Index(fields=['statut'], name='attendance__statut_e799b5_idx'), models.Index(fields=['date'], name='attendance__date_110d5b_idx')],
                'unique_together': {('personnel', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SommairePaiePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField()),
                ('annee', models.PositiveSmallIntegerField()),
                ('nb_jours_travailles', models.PositiveSmallIntegerField(default=0)),
                ('nb_jours_absence', models.PositiveSmallIntegerField(default=0, help_text='Absences non justifiées (déductibles de la paie)')),
                ('nb_jours_conge', models.PositiveSmallIntegerField(default=0, help_text='Congés justifiés (non déduits)')),
                ('nb_jours_retard', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sommaires_paie', to='users.personnel')),
            ],
            options={
                'verbose_name': 'Sommaire Paie Personnel',
                'verbose_name_plural': 'Sommaires Paie Personnel',
                'ordering': ['-annee', '-mois'],
                'indexes': [models.Index(fields=['personnel', 'annee', 'mois'], name='attendance__personn_bd5e8e_idx')],
                'unique_together': {('personnel', 'mois', 'annee')},
            },
        ),
    ]
